version: '3.1'

# when port 80 couldnt be bound, stop iis

services: 
  api:
    image: lunch-api:latest
    build: ./Lunch
    volumes:
      - ./Lunch:/lunch/Lunch
    ports:
      - "80:5000"
    depends_on:
      - database
    links:
      - database

  database:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_database
    secrets:
      - postgres_password
      - postgres_user
      - postgres_database
    volumes:
      - lunch-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  lunch-database:
    external: true

# secrets:
#   postgres_user:
#     external: true
#   postgres_password:
#     external: true
#   postgres_database:
#     external: true
    
secrets:
  postgres_user:
    file: postgres_user.txt
  postgres_password:
    file: postgres_password.txt
  postgres_database:
    file: postgres_database.txt